(function(){"use strict";
var API="https://script.google.com/macros/s/AKfycbx6IwMFf2plAq7i8qf8qF6f6MMC-1-WynAqn1ZRqCZrVqHeE9a1ygSSTzp5uOf0L3bn/exec";
var PLANNING_API="https://script.google.com/macros/s/AKfycbxOE2bAsnGKn1TvOlxBK1qJpe2nblhC4l8YWmAxTUe3VM383YaNrPmH3i1U2g-Sp7LJxA/exec";

function jsonpPlanning(params){return new Promise(function(resolve,reject){var cb="abPlanningSync_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),timer=setTimeout(function(){nettoyer();reject(new Error("relecture Planning impossible"))},15000);function nettoyer(){clearTimeout(timer);if(s.parentNode)s.remove();try{delete window[cb]}catch(e){window[cb]=void 0}}window[cb]=function(data){nettoyer();resolve(data)};s.onerror=function(){nettoyer();reject(new Error("relecture Planning impossible"))};var q=new URLSearchParams(Object.assign({},params,{callback:cb,_ts:String(Date.now())}));s.src=PLANNING_API+"?"+q.toString();document.head.appendChild(s)})}

async function retrouverIdPlanning(nom){var liste=await jsonpPlanning({action:"getChantiers"});var cible=String(nom||"").trim().toLowerCase(),matches=(Array.isArray(liste)?liste:[]).filter(function(c){return String(c.nom||"").trim().toLowerCase()===cible}).sort(function(a,b){return Number(b.id)-Number(a.id)});return matches[0]&&matches[0].id||""}

function valeur(params,nom,fallback){var v=params&&params.get?params.get(nom):null;return v===null||v===undefined||v===""?fallback:v}

async function sync(params,response){var pid=String(valeur(params,"id","")||response&&(response.id||response.chantierId||(response.chantier&&response.chantier.id))||"").trim();if(!pid)pid=String(await retrouverIdPlanning(valeur(params,"nom",""))||"").trim();if(!pid)throw new Error("identifiant Planning introuvable");
var g=await fetch(API+"?_ts="+Date.now()),j=await g.json();if(!j||!j.ok)throw new Error(j&&j.error||"lecture Yaya impossible");var a=Array.isArray(j.data&&j.data.chantiers)?j.data.chantiers:[];
var index=a.findIndex(function(c){return String(c.sourcePlanningId||"")===pid||String(c.id||"")==="planning-"+pid});
var nom=String(valeur(params,"nom",index>=0?a[index].nom:"")||"").trim();var dateDebut=valeur(params,"dateDebut",index>=0?a[index].dateDebut||"":"");var dateFin=valeur(params,"dateFin",index>=0?a[index].dateFin||dateDebut:dateDebut);var dateSignature=valeur(params,"dateSignature",index>=0?a[index].dateSignature||"":"");var typeChantier=valeur(params,"typeChantier",index>=0?a[index].typeChantier||"Rénovation":"Rénovation");
if(index>=0){var existant=a[index];a[index]=Object.assign({},existant,{id:existant.id||"planning-"+pid,nom:nom,dateDebut:dateDebut,dateFin:dateFin,dateSignature:dateSignature,typeChantier:typeChantier,source:"AB Planning",sourcePlanningId:pid,majDepuisPlanningLe:new Date().toISOString()})}else{a.push({id:"planning-"+pid,nom:nom,numero:"",montantDevisHT:0,statut:"En cours",notes:String(valeur(params,"description","")||"").trim(),dateDebut:dateDebut,dateFin:dateFin,dateSignature:dateSignature,typeChantier:typeChantier,source:"AB Planning",sourcePlanningId:pid,creeDepuisPlanningLe:new Date().toISOString()})}
var w=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"setChantiers",data:a})}),x=await w.json();if(!x||!x.ok)throw new Error(x&&x.error||"enregistrement Yaya impossible")}

new MutationObserver(function(ms){ms.forEach(function(m){m.addedNodes.forEach(function(n){if(!n||n.tagName!=="SCRIPT"||!n.src)return;var u;try{u=new URL(n.src)}catch(e){return}var action=u.searchParams.get("action");if(action!=="createChantier"&&action!=="updateChantier")return;var c=u.searchParams.get("callback"),o=c&&window[c];if(typeof o!=="function")return;window[c]=function(r){o(r);if(r&&(r.success||r.ok)){sync(u.searchParams,r).catch(function(e){console.error("Synchronisation vers Yaya :",e);alert("Le chantier est enregistré dans le Planning, mais la synchronisation vers Yaya a échoué.")})}}})})}).observe(document.documentElement,{childList:true,subtree:true});
})();
