import React, { createContext, useState, useEffect, useCallback } from "react";
import * as api from "../utils/api";
export const AppContext=createContext();
export const AppProvider=({children})=>{
 const[ouvriers,setOuvriers]=useState([]),[chantiers,setChantiers]=useState([]),[affectations,setAffectations]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[lastUpdated,setLastUpdated]=useState(null);
 const loadData=useCallback(async(showLoader=false)=>{if(showLoader)setLoading(true);try{const data=await api.getAll();if(data?.error)throw new Error(data.error);setOuvriers(Array.isArray(data?.ouvriers)?data.ouvriers:[]);setChantiers(Array.isArray(data?.chantiers)?data.chantiers:[]);setAffectations(Array.isArray(data?.affectations)?data.affectations:[]);setError(null);setLastUpdated(new Date());}catch(err){console.error("Error loading data:",err);setError(err.message);}finally{if(showLoader)setLoading(false);}},[]);
 useEffect(()=>{let actif=true;(async()=>{if(actif)await loadData(true);})();const interval=setInterval(()=>{if(actif)loadData(false);},30000);return()=>{actif=false;clearInterval(interval);};},[loadData]);
 const addOuvrier=async(nom,type,metier)=>{const r=await api.createOuvrier(nom,type,metier);if(r.success)await loadData(false);return r;};
 const updateOuvrier=async(id,nom,type,metier,statut,ordre="",separateurApres=false,refresh=true)=>{const r=await api.updateOuvrier(id,nom,type,metier,statut,ordre,separateurApres);if(r.success&&refresh)await loadData(false);return r;};
 const addChantier=async(nom,dateDebut,dateFin,description)=>{const r=await api.createChantier(nom,dateDebut,dateFin,description);if(r.success)await loadData(false);return r;};
 const updateChantier=async(id,nom,dateDebut,dateFin,description,statut)=>{const r=await api.updateChantier(id,nom,dateDebut,dateFin,description,statut);if(r.success)await loadData(false);return r;};
 const addAffectation=async(ouvrierID,chantierId,dateDebut,dateFin,tache,nomAffectation="",typeAffectation="CHANTIER")=>{let cid=chantierId||"",nom=nomAffectation||"",type=typeAffectation||"CHANTIER";if(String(cid).startsWith("__LIBRE__:")){nom=String(cid).slice(10).trim();cid="";type="HORS_GANTT";}const r=await api.createAffectation(ouvrierID,cid,dateDebut,dateFin,tache,nom,type);if(r.success)await loadData(false);return r;};
 const updateAffectation=async(id,dateDebut,dateFin,tache,statut,nomAffectation="",chantierId="")=>{const r=await api.updateAffectation(id,dateDebut,dateFin,tache,statut,nomAffectation,chantierId);if(r.success)await loadData(false);return r;};
 const deleteAffectation=async id=>{const r=await api.deleteAffectation(id);if(r.success)await loadData(false);return r;};
 const getOuvrierById=id=>ouvriers.find(o=>Number(o.id)===Number(id));
 const getChantierId=id=>chantiers.find(c=>Number(c.id)===Number(id));
 const getAffectationsByOuvrier=ouvrierID=>affectations.filter(a=>Number(a.ouvrierID)===Number(ouvrierID));
 const getAffectationsByChantier=chantierId=>affectations.filter(a=>Number(a.chantierId)===Number(chantierId));
 return <AppContext.Provider value={{ouvriers,chantiers,affectations,loading,error,lastUpdated,addOuvrier,updateOuvrier,addChantier,updateChantier,addAffectation,updateAffectation,deleteAffectation,getOuvrierById,getChantierId,getAffectationsByOuvrier,getAffectationsByChantier,loadData}}>{children}</AppContext.Provider>;
};
